# -*- coding: utf-8 -*-
"""MLPROJECT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fUv8gWTZZLWPKunTjQf70-PeARFkv_L9
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.pipeline import Pipeline

from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    roc_curve,
    auc
)


# ==========================================
# 1. LOAD DATASET
# ==========================================

df = pd.read_csv("heart 2.csv")

print("Dataset Shape:", df.shape)

print("\nFirst 5 Rows:")
print(df.head())

print("\nMissing Values:")
print(df.isnull().sum())

print("\nDuplicate Rows:", df.duplicated().sum())


# ==========================================
# 2. REMOVE DUPLICATES
# ==========================================

df = df.drop_duplicates()

print("\nShape after removing duplicates:", df.shape)


# ==========================================
# 3. SEPARATE FEATURES AND TARGET
# ==========================================

X = df.drop("HeartDisease", axis=1)
y = df["HeartDisease"]


# ==========================================
# 4. IDENTIFY DATA TYPES
# ==========================================

categorical_columns = X.select_dtypes(
    include=["object"]
).columns.tolist()

numerical_columns = X.select_dtypes(
    exclude=["object"]
).columns.tolist()

print("\nCategorical Features:")
print(categorical_columns)

print("\nNumerical Features:")
print(numerical_columns)


# ==========================================
# 5. PREPROCESSING
# ==========================================
# Numerical data -> StandardScaler
# Categorical data -> OneHotEncoder

preprocessor = ColumnTransformer(
    transformers=[
        (
            "numerical",
            StandardScaler(),
            numerical_columns
        ),
        (
            "categorical",
            OneHotEncoder(
                handle_unknown="ignore",
                sparse_output=False
            ),
            categorical_columns
        )
    ]
)


# ==========================================
# 6. SPLIT DATA
# ==========================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("\nTraining Data:", X_train.shape)
print("Testing Data:", X_test.shape)


# ==========================================
# 7. CREATE ML MODELS
# ==========================================

models = {

    "Logistic Regression":
        LogisticRegression(max_iter=1000),

    "KNN":
        KNeighborsClassifier(n_neighbors=5),

    "Decision Tree":
        DecisionTreeClassifier(random_state=42),

    "Random Forest":
        RandomForestClassifier(
            n_estimators=100,
            random_state=42
        ),

    "SVM":
        SVC(
            probability=True,
            random_state=42
        ),

    "Naive Bayes":
        GaussianNB()
}


# ==========================================
# 8. TRAIN AND TEST MODELS
# ==========================================

results = []
trained_models = {}

for name, model in models.items():

    pipeline = Pipeline(
        steps=[
            ("preprocessing", preprocessor),
            ("model", model)
        ]
    )

    # Train the model
    pipeline.fit(X_train, y_train)

    # Make predictions
    prediction = pipeline.predict(X_test)

    # Calculate metrics
    accuracy = accuracy_score(y_test, prediction)

    precision = precision_score(
        y_test,
        prediction,
        zero_division=0
    )

    recall = recall_score(
        y_test,
        prediction,
        zero_division=0
    )

    f1 = f1_score(
        y_test,
        prediction,
        zero_division=0
    )

    # Calculate AUC
    probability = pipeline.predict_proba(X_test)[:, 1]

    fpr, tpr, _ = roc_curve(
        y_test,
        probability
    )

    roc_auc = auc(fpr, tpr)

    # Save results
    results.append([
        name,
        accuracy,
        precision,
        recall,
        f1,
        roc_auc
    ])

    trained_models[name] = pipeline

    # Display results
    print("\n===================================")
    print(name)
    print("===================================")

    print("Accuracy :", round(accuracy, 4))
    print("Precision:", round(precision, 4))
    print("Recall   :", round(recall, 4))
    print("F1 Score :", round(f1, 4))
    print("AUC      :", round(roc_auc, 4))


# ==========================================
# 9. FINAL RESULTS TABLE
# ==========================================

results_df = pd.DataFrame(
    results,
    columns=[
        "Model",
        "Accuracy",
        "Precision",
        "Recall",
        "F1 Score",
        "AUC"
    ]
)

print("\n===================================")
print("FINAL MODEL RESULTS")
print("===================================")

print(
    results_df.to_string(
        index=False
    )
)


# ==========================================
# 10. FIND BEST FIT MODEL
# ==========================================
# Best model is selected using F1 Score.

best_index = results_df["F1 Score"].idxmax()

best_model_name = results_df.loc[
    best_index,
    "Model"
]

best_accuracy = results_df.loc[
    best_index,
    "Accuracy"
]

best_precision = results_df.loc[
    best_index,
    "Precision"
]

best_recall = results_df.loc[
    best_index,
    "Recall"
]

best_f1 = results_df.loc[
    best_index,
    "F1 Score"
]

best_auc = results_df.loc[
    best_index,
    "AUC"
]

print("\n===================================")
print("BEST FIT MODEL")
print("===================================")

print(
    "This is the best fit model for this:",
    best_model_name
)

print("Accuracy :", round(best_accuracy, 4))
print("Precision:", round(best_precision, 4))
print("Recall   :", round(best_recall, 4))
print("F1 Score :", round(best_f1, 4))
print("AUC      :", round(best_auc, 4))


# ==========================================
# 11. GRAPH 1 - MODEL COMPARISON
# ==========================================

print(
    "\nThis is the best fit model for this graph:",
    best_model_name
)

results_df.set_index("Model")[
    [
        "Accuracy",
        "Precision",
        "Recall",
        "F1 Score"
    ]
].plot(
    kind="bar",
    figsize=(10, 6)
)

plt.title(
    "Machine Learning Model Comparison"
)

plt.xlabel(
    "Machine Learning Models"
)

plt.ylabel(
    "Score"
)

plt.ylim(0, 1)

plt.xticks(
    rotation=45
)

plt.legend()

plt.tight_layout()

plt.show()


# ==========================================
# 12. GRAPH 2 - CORRELATION HEATMAP
# ==========================================

print(
    "\nThis is the best fit model for the prediction:",
    best_model_name
)

# Create a copy only for correlation visualization
heatmap_df = df.copy()

# Convert categorical columns to numbers only for the heatmap
for column in heatmap_df.columns:

    if heatmap_df[column].dtype == "object":

        heatmap_df[column] = pd.factorize(
            heatmap_df[column]
        )[0]

plt.figure(
    figsize=(10, 7)
)

sns.heatmap(
    heatmap_df.corr(),
    annot=True,
    cmap="coolwarm",
    fmt=".2f"
)

plt.title(
    "Correlation Heatmap"
)

plt.tight_layout()

plt.show()


# ==========================================
# 13. GRAPH 3 - CHEST PAIN VS HEART DISEASE
# ==========================================

print(
    "\nChest Pain Type vs Heart Disease"
)

# Use the original dataset before encoding
original_df = pd.read_csv("heart 2.csv")

plt.figure(
    figsize=(8, 5)
)

sns.countplot(
    data=original_df,
    x="ChestPainType",
    hue="HeartDisease"
)

plt.title(
    "Chest Pain Type vs Heart Disease"
)

plt.xlabel(
    "Chest Pain Type"
)

plt.ylabel(
    "Number of Patients"
)

plt.tight_layout()

plt.show()


# ==========================================
# 14. GRAPH 4 - CONFUSION MATRIX
# ==========================================
# Show the confusion matrix of the best model.

print(
    "\nThis is the best fit model for the Confusion Matrix:",
    best_model_name
)

best_model = trained_models[
    best_model_name
]

best_prediction = best_model.predict(
    X_test
)

cm = confusion_matrix(
    y_test,
    best_prediction
)

plt.figure(
    figsize=(5, 4)
)

sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    cmap="Blues"
)

plt.title(
    best_model_name +
    " - Confusion Matrix"
)

plt.xlabel(
    "Predicted"
)

plt.ylabel(
    "Actual"
)

plt.tight_layout()

plt.show()


# ==========================================
# 15. GRAPH 5 - ROC CURVE
# ==========================================

print(
    "\nThis is the best fit model for the ROC Curve:",
    best_model_name
)

plt.figure(
    figsize=(8, 6)
)

for name, pipeline in trained_models.items():

    probability = pipeline.predict_proba(
        X_test
    )[:, 1]

    fpr, tpr, _ = roc_curve(
        y_test,
        probability
    )

    roc_auc = auc(
        fpr,
        tpr
    )

    plt.plot(
        fpr,
        tpr,
        label=
        name +
        " (AUC = " +
        str(round(roc_auc, 2)) +
        ")"
    )


# Random classifier line

plt.plot(
    [0, 1],
    [0, 1],
    "k--",
    label="Random"
)

plt.xlabel(
    "False Positive Rate"
)

plt.ylabel(
    "True Positive Rate"
)

plt.title(
    "ROC Curve Comparison"
)

plt.legend(
    loc="lower right"
)

plt.grid()

plt.tight_layout()

plt.show()


# ==========================================
# 16. SAVE RESULTS
# ==========================================

results_df.to_csv(
    "heart_disease_results.csv",
    index=False
)


# ==========================================
# 17. FINAL MESSAGE
# ==========================================

print("\n===================================")
print("PROGRAM COMPLETED SUCCESSFULLY")
print("===================================")

print(
    "Results saved as: heart_disease_results.csv"
)

print(
    "Best fit model:",
    best_model_name
)